#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

$HOME/.config/polybar/launch.sh

bspc monitor -d I II III IV V VI VII VIII

bspc config border_width         1 
bspc config window_gap          10

bspc config focused_border_color "#ffffff"
bspc config normal_border_color "#630330"
bspc config active_border_color "#ffffff"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Viewnior state=floating
bspc rule -a firefox desktop='^2'
bspc rule -a Thunar desktop='^3'
bspc rule -a Code desktop='^4'
bspc rule -a Gimp desktop='^6' state=floating follow=on
bspc rule -a Inkscape dekstop='^6'
bspc rule -a discord desktop='^8'
bspc rule -a obs desktop='^8'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
