#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

xrandr --output DP1 --off --output DP2 --mode 1280x1024 --pos 1920x56 --rotate normal --output HDMI1 --off --output HDMI2 --primary --mode 1920x1080 --pos 0x0 --rotate normal --output VIRTUAL1 --off

$HOME/.config/polybar/launch.sh

bspc monitor HDMI2 -d I II III IV V VI VII
bspc monitor DP2 -d VIII XI

bspc config border_width         1 
bspc config window_gap          10

bspc config focused_border_color "#ffffff"
bspc config normal_border_color "#630330"
bspc config active_border_color "#ffffff"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Viewnior state=floating
bspc rule -a scrcpy state=floating
bspc rule -a firefox desktop='^2'
bspc rule -a Code desktop='^3'
bspc rule -a Insomnia desktop='^4'
bspc rule -a obsidian desktop='^5'
bspc rule -a Thunar desktop='^6'
bspc rule -a Gimp desktop='^7' state=floating follow=on
bspc rule -a Inkscape dekstop='^7'
bspc rule -a discord desktop='^8'
bspc rule -a obs desktop='^8'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

